# This is a basic workflow to help you get started with Actions

name: OWASP Database Maintenance

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Run at 5:12 every day
  schedule:
     - cron: "12 5 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  update-database:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Caching for the Dependency Check Database
      #
      # A we have a unique run IT / Attempt we will never restore
      # using the key, instead we restore the most recent and save
      # using the unique key.
      - name: Cache Dependency Check Database
        id: cache-database
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/owasp-database
          key: owasp-database-${{ github.run_id }}-${{ github.run_attempt }}
          restore-keys: owasp-database-

      # Restore Dependency Check CLI from Cache
      - name: Cache Dependency Check Installation
        id: cache-installation
        uses: actions/cache/restore@v4
        with:
          path: ${{ github.workspace }}/dependency-check
          key: dependency-check-${{ vars.DEPENDENCY_CHECK_VERSION }}
          fail-on-cache-miss: true

      # Populate a properties file with secrets
      - name: Populate Dependency Check Properties
        run: |
          echo "analyzer.ossindex.password=${{ secrets.OSS_INDEX_PASSWORD }}" > dependency-check.properties
          ls -l
          cat dependency-check.properties

      # Update Database
      - name: Update OWASP Database
        run: ./dependency-check/bin/dependency-check.sh --updateonly --data=owasp-database --nvdApiKey=${{ secrets.NVD_API_KEY }} --ossIndexUsername=${{ secrets.OSS_INDEX_USERNAME }} --propertyfile=dependency-check.properties --log=dependency-check.log

      # Upload the log files
      - name: Upload Log File
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: log-files
          path: ~/work/**/*.log